import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import StoryWriter from "@/components/StoryWriter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" flex flex-col min-h-screen pr-4 pl-4 pb-4 ">
        <div className=""></div>
        <Header/>
        {children}
      </body> 
    </html>
  );
}
